### ISSUE TITLE
IC50 convention

### ISSUE THREAD

**Issue by Ryan-Bringenberg** [bio-ml/pyzyme#5]
In the 3PL model you have

# Use of a three parameter model here sets the min at zero.
    def formula(X, A, B, C):
        return A / (1 + (X / C)**B)

the 4PL model is f(x) = D - (A - D)/(1 + X/C)**B). 
A is typically defined as the minimum response, which is being simplified to zero for biological relevance. We should use consistent naming.

**Comment by iansind** [comment]
![image](https://user-images.githubusercontent.com/108632228/214474325-551d534d-6e9c-4c86-b150-8ff86b257330.png)
D is the min here, unless this is wrong.
https://www.aatbio.com/tools/ic50-calculator

**Comment by iansind** [comment]
We'll just change the variables to more intuitive labels rather than A/B/C

**Comment by iansind** [comment]
Variable naming has been updated.
